name: MacOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:      
    macos_build:
      name: Macos Build
      runs-on: macos-latest
      steps:
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.18.x'
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Dependencies
        run: curl -o Csound-MacOS-universal-6.18.1.dmg -L https://github.com/csound/csound/releases/download/6.18.1/Csound-MacOS-universal-6.18.1.dmg && ls . &&  hdiutil mount Csound-MacOS-universal-6.18.1.dmg && echo disks && diskutil list && sudo installer -pkg /Volumes/Csound-universal-6.18.1/csound-MacOS-universal-6.18.1.pkg -target /  && echo Frameworks && ls /Library/Frameworks
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_LUAJIT=OFF -DBUILD_LUA_MODULE=OFF -DBUILD_TESTS=OFF
      - name: Build 
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with: 
          name: Hypercurve_MacOS
          path: build

