name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  windows_build:
      name: Windows Build
      runs-on: windows-latest
      steps:
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.18.x'
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install Dependencies
        #run: curl.exe -L -o Csound-6.18.1-windows-x64-binaries.zip https://github.com/csound/csound/releases/download/6.18.1/Csound-6.18.1-windows-x64-binaries.zip && tar -xf Csound-6.18.1-windows-x64-binaries.zip && dir
        #curl.exe -L -o Csound-6.18.1-windows-x64-binaries.zip https://github.com/csound/csound/releases/download/6.18.1/Csound-6.18.1-windows-x64-binaries.zip; \
        #tar -xf Csound-6.18.1-windows-x64-binaries.zip; \
        #Import-Module "$env:ChocolateyInstall\helpers\chocolateyInstaller.psm1" -Force; Get-Help Update-SessionEnvironment -Full; \
        run:
          choco install -y csound; 
          mv "C:/Program Files/csound" "C:/Program Files/Csound6_x64"; 
          setx Csound "C:/Program Files/Csound6_x64"; 
          $env:PATH += ";C:/Program Files/Csound6_x64";
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_LUAJIT=OFF -DBUILD_LUA_MODULE=OFF -DBUILD_TESTS=OFF
      - name: Build 
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
